---
description: Assert files contain no inline lint-disable directives
inputs:
  allow:
    description: Allow directive pattern (space-separated)
    required: false
  count:
    default: "false"
    description: Print finding count only
    required: false
  exclude:
    description: Glob patterns to exclude files (space-separated)
    required: false
  fail-fast:
    default: "false"
    description: Exit on first finding
    required: false
  files:
    description: Target files to check (space-separated)
    required: true
  json:
    default: "false"
    description: Output findings as JSON
    required: false
  linters:
    description: Comma-separated list of linters (yamllint,pylint,mypy)
    required: true
  quiet:
    default: "false"
    description: Suppress output, exit code only
    required: false
  warn-only:
    default: "false"
    description: Always exit 0, report only
    required: false
name: Assert No Inline Lint Disables
runs:
  steps:
    - run: pip install git+https://github.com/10U-Labs-LLC/assert-no-inline-lint-disables.git
      shell: bash
    - run: |
        ARGS="--linters ${{ inputs.linters }}"
        [ "${{ inputs.quiet }}" = "true" ] && ARGS="$ARGS --quiet"
        [ "${{ inputs.count }}" = "true" ] && ARGS="$ARGS --count"
        [ "${{ inputs.json }}" = "true" ] && ARGS="$ARGS --json"
        [ "${{ inputs.fail-fast }}" = "true" ] && ARGS="$ARGS --fail-fast"
        [ "${{ inputs.warn-only }}" = "true" ] && ARGS="$ARGS --warn-only"
        for pattern in ${{ inputs.exclude }}; do
          ARGS="$ARGS --exclude '$pattern'"
        done
        for pattern in ${{ inputs.allow }}; do
          ARGS="$ARGS --allow '$pattern'"
        done
        eval "assert-no-inline-lint-disables $ARGS ${{ inputs.files }}"
      shell: bash
  using: composite
